#配置Tomcat
server:
  port: 8080
#配置数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
#配置mybatis-plus
mybatis-plus:
  typeAliasesPackage: com.legend.domain
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.legend.mapper: debug