#配置Tomcat
server:
  port: 8080
#配置数据源
spring:
  datasource:
    url: jdbc:mysql://9.134.118.210:3306/spider?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 6
      max-active: 60
      max-wait: 60000
      maxOpenPreparedStatements: 20
      min-idle: 2
      minEvictableIdleTimeMillis: 300000
      poolPreparedStatements: true
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 60000
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
#配置mybatis-plus
mybatis-plus:
  typeAliasesPackage: com.legend.domain
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.legend.mapper: debug